[Settings]
ID = "focus-retreat-center"

[build]
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.16.1"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

# Do these specific first then generic lower down
[[redirects]]
  from = "https://focusretreatcenter.com/signin"
  to = "https://app.enrollsy.com/r/gj-62Ur6OcQG7QQRu0VP5"
  status = 302

[[redirects]]
  from = "https://focusretreatcenter.com/2023/survey"
  to = "https://us14.list-manage.com/survey?u=a54483dfc73731ced2ff35a04&id=535dbf9df4&attribution=false"
  status = 302

[[redirects]]
  from = "https://focusretreatcenter.com/2022/bar-exam"
  to = "https://focusretreatcenter.com"
  status = 301

[[redirects]]
  from = "https://focusretreatcenter.com/2023/programming"
  to = "https://focusretreatcenter.com#program"
  status = 301


[[redirects]]
  from = "https://focusretreatcenter.com/contact"
  to = "https://us14.list-manage.com/contact-form?u=a54483dfc73731ced2ff35a04&form_id=33ffae0ec11579cdc44c4f30cb839689"
  status = 302

# [[redirects]]
#   from = "https://focusretreatcenter.com/apply"
#   to = "https://forms.gle/7aL9MjzP3VK7Mhdz9"
#   status = 302

[[redirects]]
  from = "http://ink.focusretreat.center/*"
  to = "https://focusretreatcenter.com/2023/inktober/"
  status = 302
  force = true

[[redirects]]
  from = "http://ink.focusretreat.center/"
  to = "https://focusretreatcenter.com/2023/inktober/"
  status = 302
  force = true

[[redirects]]
  from = "https://ink.focusretreat.center/*"
  to = "https://focusretreatcenter.com/2023/inktober/"
  status = 302
  force = true

[[redirects]]
  from = "https://ink.focusretreat.center/"
  to = "https://focusretreatcenter.com/2023/inktober/"
  status = 302
  force = true

[[redirects]]
  from = "http://code.focusretreat.center/*"
  to = "https://focusretreatcenter.com/2023/programming/"
  status = 302
  force = true

[[redirects]]
  from = "http://code.focusretreat.center"
  to = "https://focusretreatcenter.com/2023/programming/"
  status = 302
  force = true

[[redirects]]
  from = "https://code.focusretreat.center/*"
  to = "https://focusretreatcenter.com/2023/programming/"
  status = 302
  force = true

[[redirects]]
  from = "https://code.focusretreat.center"
  to = "https://focusretreatcenter.com/2023/programming/"
  status = 302
  force = true

[[redirects]]
  from = "http://focusretreat.center"
  to = "https://focusretreatcenter.com"
  status = 301
  force = true

[[redirects]]
  from = "https://focusretreat.center"
  to = "https://focusretreatcenter.com"
  status = 301
  force = true

[[redirects]]
  from = "*"
  to = "/404/index.html"
  status = 404
  force = false
