[Settings]
ID = "focus-retreat-center"

[build]
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.15.2"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[redirects]]
  from = "http://focusretreat.center"
  to = "https://focusretreatcenter.com"
  status = 301
  force = true

[[redirects]]
  from = "https://focusretreat.center"
  to = "https://focusretreatcenter.com"
  status = 301
  force = true

# [[redirects]]
#   from = "https://focusretreatcenter.com/apply"
#   to = "https://forms.gle/7aL9MjzP3VK7Mhdz9"
#   status = 307

[[redirects]]
  from = "https://focusretreatcenter.com/contact"
  to = "https://us14.list-manage.com/contact-form?u=a54483dfc73731ced2ff35a04&form_id=33ffae0ec11579cdc44c4f30cb839689"
  status = 307


